DROP DATABASE IF EXISTS courses_db;
CREATE DATABASE courses_db;

USE courses_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE role(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL,
  department_ID INT,
  FOREIGN KEY (department_ID)
  REFERENCES department(id)
  ON DELETE SET NULL
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_ID INT,
  FOREIGN KEY (role_ID)
  REFERENCES role(id)
  ON DELETE SET NULL,
  manager_ID INT,
  FOREIGN KEY (manager_ID)
  REFERENCES employee(id)
  ON DELETE SET NULL
);


